name: Setup and Test Input Output

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.8'
  node-version:
    description: 'Node.js version'
    required: false
    default: '21'

outputs:
  repository-Owner:
    description: 'Repository owner'
    value: ${{ steps.io-vars.outputs.repository-Owner }}
  default-branch:
    description: 'Default branch of the repository'
    value: ${{ steps.io-vars.outputs.default-branch }}
  
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: variables
      id: io-vars
      shell: bash
      run: |
        echo "repository-Owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "default-branch=main" >> $GITHUB_OUTPUT
        echo "description=${{ github.description }}" >> $GITHUB_ENV