# name: my-first-action

# on:
#   push

# jobs:
#   my-first-action:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello, world!"

#   say-hello:
#       runs-on: ubuntu-latest
#       steps:
#       - run: print("Hello, world!")
#         shell: python

#   say-hello-action:
#       runs-on: ubuntu-latest
#       steps:
#       - uses: actions/hello-world-docker-action@v1
#         with:
#           who-to-greet: 'Mona the Octocat'
