name: IO Usage

on: push

jobs:
  io-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup and Test Input Output
        id: io-vars
        uses: ./.github/actions/io-actions
        with:
          python-version: '3.8'
          node-version: '21'

      - name: Display Outputs
        run: |
          echo "Repository Owner: ${{ steps.io-vars.outputs.repository-Owner }}"
          echo "Default Branch: ${{ steps.io-vars.outputs.default-branch }}"
          echo "Repo description: ${{ steps.io-vars.outputs.description }}"